# validate YAML
# https://codebeautify.org/yaml-validator

on:
  push:
    branches:
      - master
  # workflow_dispatch is required in order to manually run this workflow
  workflow_dispatch:
  schedule:
    # run weekly on Mondays
    - cron: "0 13 * * 1"

name: Build and Save Docker Image

jobs:
  build:
    name: Build and Save Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push docker
        id: docker_build
        # https://github.com/docker/build-push-action
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/firefly2442/docker-celery-worker:latest
          platforms: linux/amd64,linux/arm64
          # https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md
          cache-from: type=registry,ref=ghcr.io/firefly2442/docker-celery-worker:latest
          cache-to: type=inline